### PR TITLE
hardware_booster_hidl: Boosting ala hybris, attempt 2

### PR DESCRIPTION
**Pull request by fredldotme**
Same as https://github.com/ubports/platform-api/pull/9 but with a fix to failing dlopen and dlsym.

### CODE REVIEW

**Comment by UniversalSuperBox** [comment]
Good news: this doesn't cause the Volla Phone to lose all ability to control the display this time. :)

**Comment by fredldotme** [comment]
Let me know when it's best to remove the draft status.

**Comment by fredldotme** [comment]
Requires this change on the Halium side, since we agreed to switch the target branch to android9:
https://github.com/Halium/android/pull/67

**Comment by peat-psuwit** [comment]
Do you have an example of an "advanced port"? I just wonder what the other side looks like. Also, why does the function name have to be dynamically determined by an Android property?

**Comment by fredldotme** [comment]
> Do you have an example of an "advanced port"? I just wonder what the other side looks like. Also, why does the function name have to be dynamically determined by an Android property?

This is based on what Canonical did for the M10 tablet (note the ubuntu.booster.* properties): https://lists.launchpad.net/ubuntu-phone/msg19994.html

Here is an example implementation for the Pixel 3a (and Xperia X which basically uses the same): https://github.com/fredldotme/android_device_google_bonito/blob/halium-9.0/booster/booster.cpp

**Comment by mariogrip** [comment]
Since we don't use *closed* binaries anymore, i guess it would be ok to keep the function (and booster lib name) static. This way we dont need the prop at all as we can *check if the library exists* instead? This simplifies it a bit no?

**Comment by fredldotme** [comment]
> Since we don't use _closed_ binaries anymore, i guess it would be ok to keep the function (and booster lib name) static. This way we dont need the prop at all as we can _check if the library exists_ instead? This simplifies it a bit no?

I'm in favor of that in the long run, but the Xperia X already uses this. Something to keep in mind when we want to unify the codebase.

What I would actually propose in the long run is a custom service (call it lomiri-perf-service) on the host side which reacts to repowerd events and uses a well-defined interface to interact with the Halium-provided library which then executes whatever it needs.

**Comment by mariogrip** [comment]
> > Since we don't use _closed_ binaries anymore, i guess it would be ok to keep the function (and booster lib name) static. This way we dont need the prop at all as we can _check if the library exists_ instead? This simplifies it a bit no?
> 
> I'm in favor of that in the long run, but the Xperia X already uses this. Something to keep in mind when we want to unify the codebase.
> 
> What I would actually propose in the long run is a custom service (call it lomiri-perf-service) on the host side which reacts to repowerd events and uses a well-defined interface to interact with the Halium-provided library which then executes whatever it needs.

I agree, good point. Lets merge this as a short term thing

**Comment by Flohack74** [comment]
Do we have this on the board already?

**Comment by fredldotme** [comment]
> Do we have this on the board already?

Yes, titled "Android 9: Allow booster libraries to act upon screen on/off events".

**Pull request merged**
