### PR TITLE
Add support for gyroscope, magnetic, pressure and temperature sensors

### PR DESCRIPTION
**Pull request by Flohack74**
Thanks to Gerry Boland we can add this functionality now.

### CODE REVIEW

**Comment by gerboland** [comment]
+1 from me, thanks for the credit :)

**Comment by Flohack74** [comment]
Well we have to say thank you! Its not only adding great value but will be a good template for other sensors, to see what is needed to connect them. Thinking of a step counter e.g.

**Comment by UniversalSuperBox** [comment]
This is mergeable, but these sensors working isn't likely to last as we look to move toward sensorfw from platform-api. @peat-psuwit what do you think? Will platform-api remain for sensors in 20.04? Is it worth merging this for 16.04?

(Also the tests failed after I merged between this and xenial, good thing we caught that early)

**Comment by peat-psuwit** [comment]
Even if it's not going to last, I guess it's worth merging anyway. Ubuntu Touch from 20.04 is not going to be finished for at least 6 months or so (and I'm not sure about the upper bound...).

I still don't know if platform-api will stay for 20.04 until I get to assess the API surface of it. I _guess_ the sensor part can be replaced with sensorfw, but I'm not sure about the e.g. location part of it, and I don't even know yet which parts are available for evaluation.

**Comment by Flohack74** [comment]
So I tried again on bacon:
grafik
grafik
I guess its good to go !

**Pull request merged**
